### ISSUE TITLE
Avoid passwords appearing in log via reading from file

### ISSUE THREAD

**Issue by nakami** [DanielVeldkamp/PwnedPasswordsChecker#1]
- could use argparse
- if `-f FILE` or `--file FILE` argument is provided, read that file

**Comment by DanielVeldkamp** [comment]
Lukas Dachtler made his own [implementation](https://github.com/lukas-dachtler/pwned.py) which he updated to support reading (multiple passwords) from file. 

It's definitely a good idea to make it so the passwords don't appear in logs, but I think not being able to pass the passwords as an argument makes it annoying to use. Is there another way of preventing this issue?

**Comment by nakami** [comment]
Oh woups, did a pull request already. 😄

**Comment by DanielVeldkamp** [comment]
Thanks, I merged it, looks good!
